import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createInterface, type Interface } from 'node:readline';
import { defineCommand, runMain } from 'citty';
import { request } from 'undici';
import { parseEnv } from '../config/env';

/** readline "secret" mode trick: override the private _writeToOutput. */
interface MaskableInterface extends Interface {
  _writeToOutput?: (s: string) => void;
}

function ask(rl: Interface, prompt: string, defaultValue?: string): Promise<string> {
  return new Promise((resolvePromise) => {
    const hint = defaultValue !== undefined ? ` [${defaultValue}]` : '';
    rl.question(`${prompt}${hint}: `, (answer) => {
      const trimmed = answer.trim();
      resolvePromise(trimmed.length === 0 && defaultValue !== undefined ? defaultValue : trimmed);
    });
  });
}

async function askSecret(rl: MaskableInterface, prompt: string): Promise<string> {
  const original = rl._writeToOutput;
  rl._writeToOutput = function (str: string) {
    if (str.trim().length === 0 || str === '\n' || str === '\r\n') {
      (this as unknown as { output: NodeJS.WritableStream }).output.write(str);
    } else {
      (this as unknown as { output: NodeJS.WritableStream }).output.write('*');
    }
  };
  try {
    return await ask(rl, prompt);
  } finally {
    if (original) {
      rl._writeToOutput = original;
    } else {
      delete rl._writeToOutput;
    }
    process.stdout.write('\n');
  }
}

async function askYesNo(rl: Interface, prompt: string, defaultValue = false): Promise<boolean> {
  const yn = defaultValue ? 'Y/n' : 'y/N';
  const a = (await ask(rl, `${prompt} (${yn})`)).toLowerCase();
  if (a === '') return defaultValue;
  return a.startsWith('y');
}

function generateEncryptionKey(): string {
  return randomBytes(32).toString('hex');
}

async function testDiscordWebhook(url: string): Promise<boolean> {
  try {
    const { statusCode, body } = await request(url, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        content: '✓ eBay Volume Tool setup — webhook test (you can delete this message)',
      }),
    });
    await body.dump();
    return statusCode >= 200 && statusCode < 300;
  } catch {
    return false;
  }
}

interface EnvValues {
  NODE_ENV: string;
  LOG_LEVEL: string;
  DATABASE_URL: string;
  EBAY_ENV: string;
  EBAY_APP_ID: string;
  EBAY_CERT_ID: string;
  EBAY_DEV_ID: string;
  EBAY_REDIRECT_URI_NAME: string;
  ICECAT_USER: string;
  ICECAT_PASSWORD: string;
  DISCORD_WEBHOOK_URL: string;
  MIN_ABSOLUTE_PROFIT_EUR: string;
  MIN_MARGIN_PERCENT: string;
  DEFAULT_VAT_RATE: string;
  DEFAULT_EBAY_FEE_PERCENT: string;
  DEFAULT_EBAY_FIXED_FEE_EUR: string;
  DEFAULT_RETURN_RESERVE_PERCENT: string;
  UNDERCUT_AMOUNT_EUR: string;
  TARGET_MARGIN_MULTIPLIER: string;
  IMAGE_STORAGE_PATH: string;
  TOKEN_ENCRYPTION_KEY: string;
}

function serializeEnv(v: EnvValues): string {
  const lines = [
    '# Generated by `pnpm setup` — DO NOT commit.',
    '',
    '# ---------- App ----------',
    `NODE_ENV=${v.NODE_ENV}`,
    `LOG_LEVEL=${v.LOG_LEVEL}`,
    '',
    '# ---------- Database ----------',
    `DATABASE_URL=${v.DATABASE_URL}`,
    '',
    '# ---------- eBay API ----------',
    `EBAY_ENV=${v.EBAY_ENV}`,
    `EBAY_APP_ID=${v.EBAY_APP_ID}`,
    `EBAY_CERT_ID=${v.EBAY_CERT_ID}`,
    `EBAY_DEV_ID=${v.EBAY_DEV_ID}`,
    `EBAY_REDIRECT_URI_NAME=${v.EBAY_REDIRECT_URI_NAME}`,
    '',
    '# ---------- Icecat Open Catalog ----------',
    `ICECAT_USER=${v.ICECAT_USER}`,
    `ICECAT_PASSWORD=${v.ICECAT_PASSWORD}`,
    '',
    '# ---------- Discord ----------',
    `DISCORD_WEBHOOK_URL=${v.DISCORD_WEBHOOK_URL}`,
    '',
    '# ---------- Pricing Rules ----------',
    `MIN_ABSOLUTE_PROFIT_EUR=${v.MIN_ABSOLUTE_PROFIT_EUR}`,
    `MIN_MARGIN_PERCENT=${v.MIN_MARGIN_PERCENT}`,
    `DEFAULT_VAT_RATE=${v.DEFAULT_VAT_RATE}`,
    `DEFAULT_EBAY_FEE_PERCENT=${v.DEFAULT_EBAY_FEE_PERCENT}`,
    `DEFAULT_EBAY_FIXED_FEE_EUR=${v.DEFAULT_EBAY_FIXED_FEE_EUR}`,
    `DEFAULT_RETURN_RESERVE_PERCENT=${v.DEFAULT_RETURN_RESERVE_PERCENT}`,
    `UNDERCUT_AMOUNT_EUR=${v.UNDERCUT_AMOUNT_EUR}`,
    `TARGET_MARGIN_MULTIPLIER=${v.TARGET_MARGIN_MULTIPLIER}`,
    '',
    '# ---------- Storage ----------',
    `IMAGE_STORAGE_PATH=${v.IMAGE_STORAGE_PATH}`,
    '',
    '# ---------- Security (auto-generated) ----------',
    `TOKEN_ENCRYPTION_KEY=${v.TOKEN_ENCRYPTION_KEY}`,
    '',
  ];
  return lines.join('\n');
}

/* eslint-disable no-console -- interactive CLI wizard by design */

const command = defineCommand({
  meta: {
    name: 'setup',
    description:
      'Interactive setup wizard. Prompts for every credential + config value, writes .env with 0600 permissions.',
  },
  args: {
    envFile: { type: 'string', default: '.env' },
    skipTests: { type: 'boolean', default: false, description: 'Skip Discord webhook live test' },
  },
  async run({ args }) {
    const envPath = resolve(process.cwd(), args.envFile);

    console.log('\n=== eBay Volume Tool — Setup Wizard ===\n');

    if (existsSync(envPath)) {
      const rl0 = createInterface({ input: process.stdin, output: process.stdout });
      const overwrite = await askYesNo(rl0, `${args.envFile} already exists. Overwrite?`, false);
      rl0.close();
      if (!overwrite) {
        console.log('Aborted. Existing .env preserved.');
        return;
      }
    }

    const rl = createInterface({ input: process.stdin, output: process.stdout });

    try {
      console.log('--- Environment ---');
      const NODE_ENV = await ask(rl, 'NODE_ENV', 'development');
      const LOG_LEVEL = await ask(rl, 'LOG_LEVEL', 'info');

      console.log('\n--- Database ---');
      const DATABASE_URL = await ask(
        rl,
        'DATABASE_URL',
        'postgresql://postgres:postgres@localhost:5432/ebay_tool'
      );

      console.log('\n--- eBay API ---');
      console.log(
        '  You need Sandbox OR Production app keys from https://developer.ebay.com/my/keys'
      );
      const EBAY_ENV = await ask(rl, 'EBAY_ENV (sandbox | production)', 'sandbox');
      const EBAY_APP_ID = await ask(rl, 'EBAY_APP_ID (Client ID)');
      const EBAY_CERT_ID = await askSecret(rl, 'EBAY_CERT_ID (Client Secret, hidden)');
      const EBAY_DEV_ID = await ask(rl, 'EBAY_DEV_ID');
      const EBAY_REDIRECT_URI_NAME = await ask(
        rl,
        'EBAY_REDIRECT_URI_NAME (RuName from eBay Dev Dashboard)'
      );

      console.log('\n--- Icecat Open Catalog (register at https://icecat.biz) ---');
      const ICECAT_USER = await ask(rl, 'ICECAT_USER');
      const ICECAT_PASSWORD = await askSecret(rl, 'ICECAT_PASSWORD (hidden)');

      console.log('\n--- Discord Webhook ---');
      const DISCORD_WEBHOOK_URL = await askSecret(
        rl,
        'DISCORD_WEBHOOK_URL (https://discord.com/api/webhooks/..., hidden)'
      );

      console.log('\n--- Pricing Rules (Enter = default) ---');
      const MIN_ABSOLUTE_PROFIT_EUR = await ask(rl, 'MIN_ABSOLUTE_PROFIT_EUR', '10');
      const MIN_MARGIN_PERCENT = await ask(rl, 'MIN_MARGIN_PERCENT', '0.08');
      const DEFAULT_VAT_RATE = await ask(rl, 'DEFAULT_VAT_RATE', '0.19');
      const DEFAULT_EBAY_FEE_PERCENT = await ask(rl, 'DEFAULT_EBAY_FEE_PERCENT', '0.12');
      const DEFAULT_EBAY_FIXED_FEE_EUR = await ask(rl, 'DEFAULT_EBAY_FIXED_FEE_EUR', '0.35');
      const DEFAULT_RETURN_RESERVE_PERCENT = await ask(
        rl,
        'DEFAULT_RETURN_RESERVE_PERCENT',
        '0.03'
      );
      const UNDERCUT_AMOUNT_EUR = await ask(rl, 'UNDERCUT_AMOUNT_EUR', '0.50');
      const TARGET_MARGIN_MULTIPLIER = await ask(rl, 'TARGET_MARGIN_MULTIPLIER', '1.25');

      console.log('\n--- Storage ---');
      const IMAGE_STORAGE_PATH = await ask(rl, 'IMAGE_STORAGE_PATH', './storage/images');

      console.log('\n--- Security ---');
      console.log('  Auto-generating a 32-byte AES-256 encryption key via openssl-equivalent…');
      const TOKEN_ENCRYPTION_KEY = generateEncryptionKey();
      console.log(`  ✓ Generated (64 hex chars). Will be stored encrypted in .env.`);

      const values: EnvValues = {
        NODE_ENV,
        LOG_LEVEL,
        DATABASE_URL,
        EBAY_ENV,
        EBAY_APP_ID,
        EBAY_CERT_ID,
        EBAY_DEV_ID,
        EBAY_REDIRECT_URI_NAME,
        ICECAT_USER,
        ICECAT_PASSWORD,
        DISCORD_WEBHOOK_URL,
        MIN_ABSOLUTE_PROFIT_EUR,
        MIN_MARGIN_PERCENT,
        DEFAULT_VAT_RATE,
        DEFAULT_EBAY_FEE_PERCENT,
        DEFAULT_EBAY_FIXED_FEE_EUR,
        DEFAULT_RETURN_RESERVE_PERCENT,
        UNDERCUT_AMOUNT_EUR,
        TARGET_MARGIN_MULTIPLIER,
        IMAGE_STORAGE_PATH,
        TOKEN_ENCRYPTION_KEY,
      };

      console.log('\n--- Validating env schema ---');
      try {
        parseEnv(values as unknown as NodeJS.ProcessEnv);
        console.log('  ✓ All values pass Zod schema validation');
      } catch (err) {
        console.error(`  ✗ Schema validation failed: ${(err as Error).message}`);
        console.error('  Aborting — fix the inputs and re-run `pnpm setup`.');
        return;
      }

      writeFileSync(envPath, serializeEnv(values), { mode: 0o600, encoding: 'utf8' });
      console.log(`  ✓ Wrote ${args.envFile} (permissions 0600)`);

      if (!args.skipTests) {
        console.log('\n--- Live tests ---');
        process.stdout.write('  Testing Discord webhook… ');
        const discordOk = await testDiscordWebhook(DISCORD_WEBHOOK_URL);
        console.log(discordOk ? 'OK ✓' : 'FAILED ✗  (double-check the URL)');
      }

      console.log('\n=== Setup complete ===');
      console.log('\nNext steps:');
      console.log('  1. docker compose up -d        # start Postgres');
      console.log('  2. pnpm db:migrate             # apply DB schema');
      console.log('  3. pnpm setup:ebay-auth        # one-time OAuth consent');
      console.log('  4. pnpm setup:resolve-categories  # resolve whitelist to eBay category IDs');
      console.log('  5. pnpm cli:list-product --ean=<EAN> --cogs=<EUR>     # dry run (default)');
      console.log(
        '  6. pnpm cli:list-product --ean=<EAN> --cogs=<EUR> --publish  # actually publish to sandbox'
      );
    } finally {
      rl.close();
    }
  },
});

/* eslint-enable no-console */

await runMain(command);
