import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { z } from 'zod';
import { ConfigError } from './errors';

const categoryEntrySchema = z.object({
  name: z.string().min(1),
  ebay_category_path: z.array(z.string().min(1)).min(1),
  notes: z.string().optional(),
});

const whitelistSchema = z.array(categoryEntrySchema).min(1);

export type CategoryEntry = z.infer<typeof categoryEntrySchema>;
export type CategoryWhitelist = z.infer<typeof whitelistSchema>;

const keywordBlacklistSchema = z.object({
  _comment: z.string().optional(),
  patterns: z.array(z.string().min(1)).min(1),
});

export type KeywordBlacklist = z.infer<typeof keywordBlacklistSchema>;

/**
 * Map of category name (as defined in whitelist) → resolved eBay category ID.
 * Generated by `pnpm setup:resolve-categories`.
 */
const resolvedCategoryIdsSchema = z.record(z.string().min(1), z.string().min(1));
export type ResolvedCategoryIds = z.infer<typeof resolvedCategoryIdsSchema>;

function readJson(absPath: string): unknown {
  let raw: string;
  try {
    raw = readFileSync(absPath, 'utf8');
  } catch (cause) {
    throw new ConfigError(
      `Config file not found or unreadable: ${absPath}`,
      { path: absPath },
      { cause }
    );
  }
  try {
    return JSON.parse(raw);
  } catch (cause) {
    throw new ConfigError(
      `Config file is not valid JSON: ${absPath}`,
      { path: absPath },
      { cause }
    );
  }
}

function parseOrThrow<T>(
  schema: z.ZodType<T>,
  data: unknown,
  path: string,
  friendlyName: string
): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    const issues = result.error.issues
      .map((issue) => `  - ${issue.path.join('.') || '<root>'}: ${issue.message}`)
      .join('\n');
    throw new ConfigError(`${friendlyName} schema invalid:\n${issues}`, {
      path,
      issues: result.error.issues,
    });
  }
  return result.data;
}

/**
 * Load and validate `config-files/category-whitelist.json` relative to `projectRoot`.
 * Defaults to `process.cwd()`.
 */
export function loadCategoryWhitelist(projectRoot: string = process.cwd()): CategoryWhitelist {
  const path = resolve(projectRoot, 'config-files', 'category-whitelist.json');
  return parseOrThrow(whitelistSchema, readJson(path), path, 'category-whitelist.json');
}

export function loadKeywordBlacklist(projectRoot: string = process.cwd()): KeywordBlacklist {
  const path = resolve(projectRoot, 'config-files', 'keyword-blacklist.json');
  return parseOrThrow(keywordBlacklistSchema, readJson(path), path, 'keyword-blacklist.json');
}

/**
 * Load resolved eBay category IDs. Throws `ConfigError` with hint to run setup
 * if the file is missing — users should run `pnpm setup:resolve-categories` once.
 */
export function loadResolvedCategoryIds(projectRoot: string = process.cwd()): ResolvedCategoryIds {
  const path = resolve(projectRoot, 'config-files', 'ebay-category-ids.json');
  return parseOrThrow(
    resolvedCategoryIdsSchema,
    readJson(path),
    path,
    'ebay-category-ids.json — run `pnpm setup:resolve-categories` first'
  );
}
